### ISSUE TITLE
Don't check in compiled CSS

### ISSUE THREAD

**Issue by rhburrows** [woahdae/meals#1]
I haven't checked out how the deploy works but since the compiled css has hardcoded links to the gem locations it seems weird to me that it is in the repository. Specifically running the tests locally recreates these files and since the paths don't match for me I have to ignore them.

P.S. I've decided for now to just mention things like this through Issues because I can't think of a better way. Let me know if you have one.

**Comment by woahdae** [comment]
Glad to find stuff like this, probably works in production b/c it seems re-compiles on startup.

Fixed in [this commit](https://github.com/woahdae/meals/commit/aae5d428aab71674d8eed62653167fecf13ae04c)
